name: pertpy
channels: [conda-forge]
dependencies:
  - python=3.12
  - pip
  - pip:
      - pip          # upgrades pip inside env
      - setuptools
      - wheel
      - pertpy
      - scanpy
      - anndata
      - h5py
      - filelock
      - jax
